E_Commerce/Areas/Admin/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace E_Commerce.Areas.Admin.Models
{
    public class LoginViewModel
    {
        [Key]
        [MaxLength(50)]
        [Required(ErrorMessage = "Vui lòng nhập Email")]
        [Display(Name = "Địa chỉ Email")]
        [DataType(DataType.EmailAddress)]
        [EmailAddress(ErrorMessage = "Vui lòng nhập Email")]
        public string Email { get; set; }

        [Display(Name = "Mật Khẩu")]
        [Required(ErrorMessage = "Vui lòng nhập mật khẩu")]
        [MaxLength(30, ErrorMessage = "Mật khẩu không quá 30 kí tự")]
        public string Password { get; set; }
    }
}

E_Commerce/Areas/Admin/Controllers/AdminLoginController.cs
using E_Commerce.Extension;
using E_Commerce.Areas.Admin.Models;
using E_Commerce.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace E_Commerce.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminLoginController : Controller
    {

        private readonly MarketDBContext _context;

        public AdminLoginController(MarketDBContext context)
        {
            _context = context;
        }


        [HttpGet]
        [AllowAnonymous]
        [Route("/dang-nhap.html", Name = "Login")]
        public IActionResult Login(string returnUrl = null)
        {
            var taikhoanID = HttpContext.Session.GetString("AccountId");
            if (taikhoanID != null) return RedirectToAction("Index", "Home", new { Area = "Admin" });
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [Route("/dang-nhap.html", Name = "Login")]
        public async Task<IActionResult> Login(LoginViewModel model, string returnUrl = null)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Account kh = _context.Accounts
                        .Include(p => p.Role)
                        .SingleOrDefault(p => p.Email.ToLower() == model.Email.ToLower().Trim());

                    if (kh == null)
                    {
                        ViewBag.Error = "Thông tin đăng nhập không chính xác";
                        return View(model);
                    }
                    string pass = (model.Password.ToLower() + kh.Salt.Trim()).ToMD5();
                    if (kh.Password.Trim() != pass)
                    {
                        ViewBag.Error = "Thông tin đăng nhập không chính xác";
                        return View(model);
                    }

                    //Đăng nhập thành công
                    kh.LastLogin = DateTime.Now;
                    _context.Update(kh);
                    await _context.SaveChangesAsync();

                    var taikhoanID = HttpContext.Session.GetString("AccountId");

                    HttpContext.Session.SetString("AccountId", kh.AccountId.ToString());

                    var userClaims = new List<Claim>
                    {
                        new Claim(ClaimTypes.Name, kh.FullName),
                        new Claim(ClaimTypes.Email, kh.Email),
                        new Claim("AccountId", kh.AccountId.ToString()),
                        new Claim("RoleId", kh.RoleId.ToString()),
                        new Claim(ClaimTypes.Role, kh.Role.RoleName)
                    };

                    var grandmaIdentity = new ClaimsIdentity(userClaims, "User Identity");
                    var userPrincipal = new ClaimsPrincipal(new[] { grandmaIdentity });
                    await HttpContext.SignInAsync(userPrincipal);

                    if (Url.IsLocalUrl(returnUrl))
                    {
                        return Redirect(returnUrl);
                    }
                    return RedirectToAction("Index", "Home", new { Area = "Admin" });
                }

            }
            catch
            {
                return RedirectToAction("Login", "Home", new { Area = "Admin" });
            }
            return RedirectToAction("Login", "Home", new { Area = "Admin" });

        }

        [Route("/dang-xuat.html", Name = "Logout")]
        public async Task<IActionResult> Logout()
        {
            try
            {
                await HttpContext.SignOutAsync();
                HttpContext.Session.Remove("AccountId");
                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return RedirectToAction("Index", "Home");
            }
        }
    }
}

E_Commerce/Areas/Admin/Views/AdminLogin/Login.cshtml
@model E_Commerce.Areas.Admin.Models.LoginViewModel
@{
    ViewData["Title"] = "Login";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLoginLayout.cshtml";
}
<div class="card-body">
    <div class="d-flex align-items-center justify-content-between m-b-30">
        <img class="img-fluid" alt="" src="~/AdminAssets/images/logo/logo.png">
        <h2 class="m-b-0">Sign In</h2>
    </div>
    <form asp-area="Admin" asp-controller="AdminLogin" asp-action="Login" method="post">
        <div class="form-group">
            <label class="font-weight-semibold" for="userName">Username:</label>
            <div class="input-affix">
                <i class="prefix-icon anticon anticon-user"></i>
                <input type="text" class="form-control" asp-for="Email" placeholder="Enter your email">
            </div>
        </div>
        <div class="form-group">
            <label class="font-weight-semibold" for="password">Password:</label>
            <a class="float-right font-size-13 text-muted" href="">Forget Password?</a>
            <div class="input-affix m-b-10">
                <i class="prefix-icon anticon anticon-lock"></i>
                <input type="password" class="form-control" asp-for="Password" placeholder="Enter your password">
            </div>
        </div>
        <p class="mg-b-0 text-danger">@ViewBag.Error</a></p>
        <div class="form-group">
            <div class="d-flex align-items-center justify-content-between">
                <button class="btn btn-primary">Sign In</button>
            </div>
        </div>
    </form>
</div>