E_Commerce/Areas/Admin/Controllers/AdminTransactStatusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using E_Commerce.Models;
using Microsoft.AspNetCore.Authorization;
using AspNetCoreHero.ToastNotification.Abstractions;

namespace E_Commerce.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class AdminTransactStatusController : Controller
    {
        private readonly MarketDBContext _context;

        public INotyfService _notifyService { get; }

        public AdminTransactStatusController(MarketDBContext context, INotyfService notifyService)
        {
            _context = context;
            _notifyService = notifyService;
        }

        // GET: Admin/AdminTransactStatus
        public async Task<IActionResult> Index()
        {
            return View(await _context.TransactStatuses.ToListAsync());
        }

        // GET: Admin/AdminTransactStatus/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var transactStatus = await _context.TransactStatuses
                .FirstOrDefaultAsync(m => m.TransactStatusId == id);
            if (transactStatus == null)
            {
                return NotFound();
            }

            return View(transactStatus);
        }

        // GET: Admin/AdminTransactStatus/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminTransactStatus/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TransactStatusId,Status,Description")] TransactStatus transactStatus)
        {
            if (ModelState.IsValid)
            {
                _context.Add(transactStatus);
                _notifyService.Success("Create Success");
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(transactStatus);
        }

        // GET: Admin/AdminTransactStatus/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var transactStatus = await _context.TransactStatuses.FindAsync(id);
            if (transactStatus == null)
            {
                return NotFound();
            }
            return View(transactStatus);
        }

        // POST: Admin/AdminTransactStatus/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TransactStatusId,Status,Description")] TransactStatus transactStatus)
        {
            if (id != transactStatus.TransactStatusId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(transactStatus);
                    _notifyService.Success("Changes Success");
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TransactStatusExists(transactStatus.TransactStatusId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(transactStatus);
        }

        // GET: Admin/AdminTransactStatus/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var transactStatus = await _context.TransactStatuses
                .FirstOrDefaultAsync(m => m.TransactStatusId == id);
            if (transactStatus == null)
            {
                return NotFound();
            }

            return View(transactStatus);
        }

        // POST: Admin/AdminTransactStatus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var transactStatus = await _context.TransactStatuses.FindAsync(id);
            _context.TransactStatuses.Remove(transactStatus);
            _notifyService.Success("Delete Success");
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TransactStatusExists(int id)
        {
            return _context.TransactStatuses.Any(e => e.TransactStatusId == id);
        }
    }
}

E_Commerce/Areas/Admin/Views/AdminTransactStatus/Create.cshtml
@model E_Commerce.Models.TransactStatus

@{
    ViewData["Title"] = "Thêm Mới Trạng Thái";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <h2 class="header-title">Trạng Thái Giao Dịch</h2>
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <span class="breadcrumb-item active">Thêm Mới Giao Dịch</span>
        </nav>
    </div>
</div>
<form method="post" asp-area="Admin" asp-controller="AdminTransactStatus" asp-action="Create">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-layout">
        <div class="col-lg-4">
            <div class="form-group">
                <label class="form-control-label">Trạng Thái: <span class="text-danger">*</span></label>
                <input class="form-control" type="text" asp-for="Status">
            </div>
        </div><!-- col-4 -->
        <div class="col-lg-4">
            <div class="form-group">
                <label class="form-control-label">Mô Tả: <span class="text-danger">*</span></label>
                <input class="form-control" type="text" asp-for="Description">
            </div>
        </div><!-- col-4 -->

        <div class="form-layout-footer m-l-15">
            <button class="btn btn-primary bd-0">Save</button>
            <button class="btn btn-secondary bd-0" asp-area="Admin" asp-controller="AdminTransactStatus" asp-action="Index">Back To List</button>
        </div><!-- form-layout-footer -->
    </div><!-- form-layout -->
</form>

E_Commerce/Areas/Admin/Views/AdminTransactStatus/Delete.cshtml
@model E_Commerce.Models.TransactStatus

@{
    ViewData["Title"] = "Xóa Trạng Thái";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <h2 class="header-title">Trạng Thái Giao Dịch</h2>
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <span class="breadcrumb-item active">Xác Nhận Xóa Trạng Thái Giao Dịch</span>
        </nav>
    </div>
</div>
<div class="row">
    <div class="col-lg-4">
        <div class="form-group">
            <label class="form-control-label">Trạng Thái: <span class="text-danger">*</span></label>
            <input disabled class="form-control" type="text" asp-for="Status">
        </div>
    </div><!-- col-4 -->
    <div class="col-lg-4">
        <div class="form-group">
            <label class="form-control-label">Mô Tả: <span class="text-danger">*</span></label>
            <input disabled class="form-control" type="text" asp-for="Description">
        </div>
    </div><!-- col-4 -->
</div><!-- form-layout -->
<form asp-action="Delete" asp-controller="AdminTransactStatus" asp-route-id="@Model.TransactStatusId">
    <input type="hidden" asp-for="TransactStatusId" />
    <input type="submit" value="Delete" class="btn btn-danger" /> |
    <button class="btn btn-secondary bd-0" asp-area="Admin" asp-controller="AdminTransactStatus" asp-action="Index">Back To List</button>
</form>

E_Commerce/Areas/Admin/Views/AdminTransactStatus/Details.cshtml
@model E_Commerce.Models.TransactStatus

@{
    ViewData["Title"] = "Chi Tiết Trạng Thái";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="page-header">
    <h2 class="header-title">Trạng Thái Giao Dịch</h2>
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <span class="breadcrumb-item active">Chi Tiết Giao Dịch</span>
        </nav>
    </div>
</div>
<div class="row">
    <div class="col-lg-4">
        <div class="form-group">
            <label class="form-control-label">Trạng Thái: <span class="text-danger">*</span></label>
            <input disabled class="form-control" type="text" asp-for="Status">
        </div>
    </div><!-- col-4 -->
    <div class="col-lg-4">
        <div class="form-group">
            <label class="form-control-label">Mô Tả: <span class="text-danger">*</span></label>
            <input disabled class="form-control" type="text" asp-for="Description">
        </div>
    </div><!-- col-4 -->
</div><!-- form-layout -->
<form>
    <div class="form-layout-footer">
        <button class="btn btn-secondary bd-0" asp-area="Admin" asp-controller="AdminTransactStatus" asp-action="Index">Back To List</button>
    </div><!-- form-layout-footer -->
</form>

E_Commerce/Areas/Admin/Views/AdminTransactStatus/Edit.cshtml
@model E_Commerce.Models.TransactStatus

@{
    ViewData["Title"] = "Chỉnh Sửa Trạng Thái";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <h2 class="header-title">Trạng Thái Giao Dịch</h2>
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <span class="breadcrumb-item active">Chỉnh Sửa Giao Dịch</span>
        </nav>
    </div>
</div>
<form method="post" asp-area="Admin" asp-controller="AdminTransactStatus" asp-action="Edit">
    <input type="hidden" asp-for="TransactStatusId"/>
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-layout">
        <div class="col-lg-4">
            <div class="form-group">
                <label class="form-control-label">Trạng Thái: <span class="text-danger">*</span></label>
                <input class="form-control" type="text" asp-for="Status">
            </div>
        </div><!-- col-4 -->
        <div class="col-lg-4">
            <div class="form-group">
                <label class="form-control-label">Mô Tả: <span class="text-danger">*</span></label>
                <input class="form-control" type="text" asp-for="Description">
            </div>
        </div><!-- col-4 -->

        <div class="form-layout-footer m-l-15">
            <button class="btn btn-primary bd-0">Save Changes</button>
            <button class="btn btn-secondary bd-0" asp-area="Admin" asp-controller="AdminTransactStatus" asp-action="Index">Back To List</button>
        </div><!-- form-layout-footer -->
    </div><!-- form-layout -->
</form>

E_Commerce/Areas/Admin/Views/AdminTransactStatus/Index.cshtml
@model IEnumerable<E_Commerce.Models.TransactStatus>

@{
    ViewData["Title"] = "Phương Thức Thanh Toán";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <h2 class="header-title">Trạng Thái Giao Dịch</h2>
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <span class="breadcrumb-item active">Trạng Thái Giao Dịch</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <div class=" m-b-15">
            <a class="btn btn-primary" asp-controller="AdminTransactStatus" asp-action="Create">
                <i class="anticon anticon-plus-circle m-r-5"></i>Thêm Trạng Thái
            </a>
        </div>
        <div class="table-responsive">
            <table class="table table-hover e-commerce-table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Trạng Thái</th>
                        <th>Mô Tả</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null)
                    {
                        foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @item.TransactStatusId
                                </td>
                                <td>
                                    @item.Status
                                </td>
                                <td>
                                    @item.Description
                                </td>

                                <td class="text-right">
                                    <a class="btn btn-success btn-sm m-r-5" asp-area="Admin" asp-controller="AdminTransactStatus" asp-action="Details" asp-route-id="@item.TransactStatusId">View</a>
                                    <a class="btn btn-warning btn-sm m-r-5 text-black-50" asp-area="Admin" asp-controller="AdminTransactStatus" asp-action="Edit" asp-route-id="@item.TransactStatusId"><i class="anticon anticon-edit"></i> Update</a>
                                    <a class="btn btn-danger btn-sm m-r-5 text-white" asp-area="Admin" asp-controller="AdminTransactStatus" asp-action="Delete" asp-route-id="@item.TransactStatusId"><i class="anticon anticon-delete"></i> Delete</a>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>