E_Commerce/Areas/Admin/Controllers/AdminPaymentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using E_Commerce.Models;
using Microsoft.AspNetCore.Authorization;
using AspNetCoreHero.ToastNotification.Abstractions;

namespace E_Commerce.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class AdminPaymentsController : Controller
    {
        private readonly MarketDBContext _context;

        public INotyfService _notifyService { get; }

        public AdminPaymentsController(MarketDBContext context, INotyfService notifyService)
        {
            _context = context;
            _notifyService = notifyService;
        }

        // GET: Admin/AdminPayments
        public async Task<IActionResult> Index()
        {
            return View(await _context.Payments.ToListAsync());
        }

        // GET: Admin/AdminPayments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var payment = await _context.Payments
                .FirstOrDefaultAsync(m => m.PaymentId == id);
            if (payment == null)
            {
                return NotFound();
            }

            return View(payment);
        }

        // GET: Admin/AdminPayments/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminPayments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PaymentId,PaymentType")] Payment payment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(payment);
                _notifyService.Success("Create Success");
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(payment);
        }

        // GET: Admin/AdminPayments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var payment = await _context.Payments.FindAsync(id);
            if (payment == null)
            {
                return NotFound();
            }
            return View(payment);
        }

        // POST: Admin/AdminPayments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PaymentId,PaymentType")] Payment payment)
        {
            if (id != payment.PaymentId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(payment);
                    _notifyService.Success("Chaneges Success");
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PaymentExists(payment.PaymentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(payment);
        }

        // GET: Admin/AdminPayments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var payment = await _context.Payments
                .FirstOrDefaultAsync(m => m.PaymentId == id);
            if (payment == null)
            {
                return NotFound();
            }

            return View(payment);
        }

        // POST: Admin/AdminPayments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var payment = await _context.Payments.FindAsync(id);
            _context.Payments.Remove(payment);
            _notifyService.Success("Delete Success");
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PaymentExists(int id)
        {
            return _context.Payments.Any(e => e.PaymentId == id);
        }
    }
}

E_Commerce/Areas/Admin/Views/AdminPayments/Create.cshtml
@model E_Commerce.Models.Payment

@{
    ViewData["Title"] = "Thêm Mới Phương Thức";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<form method="post" asp-area="Admin" asp-controller="AdminPayments" asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-layout">
        <div class="row mg-b-25">
            <div class="col-lg-4">
                <div class="form-group">
                    <label class="form-control-label">Tên Phương Thức: <span class="text-danger">*</span></label>
                    <input class="form-control" type="text" asp-for="PaymentType">
                </div>
            </div><!-- col-4 -->
        </div><!-- row -->

        <div class="form-layout-footer">
            <button class="btn btn-primary bd-0">Save</button>
            <button class="btn btn-secondary bd-0" asp-area="Admin" asp-controller="AdminPayments" asp-action="Index">Back To List</button>
        </div><!-- form-layout-footer -->
    </div><!-- form-layout -->
</form>

E_Commerce/Areas/Admin/Views/AdminPayments/Delete.cshtml
@model E_Commerce.Models.Payment

@{
    ViewData["Title"] = "Chỉnh Sửa Phương Thức";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<div class="form-layout">
    <div class="row mg-b-25">
        <div class="col-lg-4">
            <div class="form-group">
                <label class="form-control-label">Tên Phương Thức: <span class="text-danger">*</span></label>
                <input class="form-control" type="text" asp-for="PaymentType" disabled>
            </div>
        </div><!-- col-4 -->
    </div><!-- row -->

    <form asp-action="Delete" asp-controller="AdminPayments"  asp-route-id="@Model.PaymentId">
        <input type="hidden" asp-for="PaymentId" />
        <input type="submit" value="Delete" class="btn btn-danger m-l-15" /> |
        <button class="btn btn-secondary bd-0" asp-area="Admin" asp-controller="AdminPayments" asp-action="Index">Back To List</button>
    </form>
</div><!-- form-layout -->

E_Commerce/Areas/Admin/Views/AdminPayments/Details.cshtml
@model E_Commerce.Models.Payment

@{
    ViewData["Title"] = "Chỉnh Sửa Phương Thức";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="form-layout">
    <div class="row mg-b-25">
        <div class="col-lg-4">
            <div class="form-group">
                <label class="form-control-label">Tên Phương Thức: <span class="text-danger">*</span></label>
                <input class="form-control" type="text" asp-for="PaymentType" disabled>
            </div>
        </div><!-- col-4 -->
    </div><!-- row -->
</div><!-- form-layout -->
<form asp-action="Delete" asp-controller="AdminPayments">
    <button class="btn btn-secondary bd-0" asp-area="Admin" asp-controller="AdminPayments" asp-action="Index">Back To List</button>
</form>

E_Commerce/Areas/Admin/Views/AdminPayments/Edit.cshtml
@model E_Commerce.Models.Payment

@{
    ViewData["Title"] = "Chỉnh Sửa Phương Thức";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<form method="post" asp-area="Admin" asp-controller="AdminPayments" asp-action="Edit">
    <input type="hidden" asp-for="PaymentId" />
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-layout">
        <div class="row mg-b-25">
            <div class="col-lg-4">
                <div class="form-group">
                    <label class="form-control-label">Tên Phương Thức: <span class="text-danger">*</span></label>
                    <input class="form-control" type="text" asp-for="PaymentType">
                </div>
            </div><!-- col-4 -->
        </div><!-- row -->

        <div class="form-layout-footer">
            <button class="btn btn-primary bd-0">Save</button>
            <button class="btn btn-secondary bd-0" asp-area="Admin" asp-controller="AdminPayments" asp-action="Index">Back To List</button>
        </div><!-- form-layout-footer -->
    </div><!-- form-layout -->
</form>

E_Commerce/Areas/Admin/Views/AdminPayments/Index.cshtml
@model IEnumerable<E_Commerce.Models.Payment>

@{
    ViewData["Title"] = "Phương Thức Thanh Toán";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <h2 class="header-title">Phương Thức Thanh Toán</h2>
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <span class="breadcrumb-item active">Phương Thức Thanh Toán</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <div class=" m-b-15">
            <a class="btn btn-primary" asp-controller="AdminPayments" asp-action="Create">
                <i class="anticon anticon-plus-circle m-r-5"></i>Thêm Phương Thức
            </a>
        </div>
        <div class="table-responsive">
            <table class="table table-hover e-commerce-table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Phương Thức</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null)
                    {
                        foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @item.PaymentId
                                </td>
                                <td>
                                    @item.PaymentType
                                </td>

                                <td class="text-right">
                                    <a class="btn btn-success btn-sm m-r-5" asp-area="Admin" asp-controller="AdminPayments" asp-action="Details" asp-route-id="@item.PaymentId">View</a>
                                    <a class="btn btn-warning btn-sm m-r-5 text-black-50" asp-area="Admin" asp-controller="AdminPayments" asp-action="Edit" asp-route-id="@item.PaymentId"><i class="anticon anticon-edit"></i> Update</a>
                                    <a class="btn btn-danger btn-sm m-r-5 text-white" asp-area="Admin" asp-controller="AdminPayments" asp-action="Delete" asp-route-id="@item.PaymentId"><i class="anticon anticon-delete"></i> Delete</a>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>