E_Commerce/Areas/Admin/Controllers/AdminPagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using E_Commerce.Models;
using PagedList.Core;
using Microsoft.AspNetCore.Http;
using Blogs.Helpers;
using System.IO;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;

namespace E_Commerce.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class AdminPagesController : Controller
    {
        private readonly MarketDBContext _context;
        public INotyfService _notifyService { get; }
        public AdminPagesController(MarketDBContext context, INotyfService notifyService)
        {
            _context = context;
            _notifyService = notifyService;
        }

        // GET: Admin/AdminPages
        public IActionResult Index(int? page)
        {
            var pageNumber = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = Utilities.PAGE_SIZE;
            var lsPages = _context.Pages
                .OrderBy(x => x.PageId);

            PagedList<Page> models = new PagedList<Page>(lsPages, pageNumber, pageSize);
            ViewBag.CurrentPage = pageNumber;
            return View(models);
        }

        // GET: Admin/AdminPages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var page = await _context.Pages
                .FirstOrDefaultAsync(m => m.PageId == id);
            if (page == null)
            {
                return NotFound();
            }

            return View(page);
        }

        // GET: Admin/AdminPages/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminPages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PageId,PageName,Contents,Thumb,Published,Title,MetaDesc,MetaKey,Alias,CreateDate,Ordering")] Page page, IFormFile fthumb)
        {
            if (ModelState.IsValid)
            {
                page.PageName = Utilities.ToTitleCase(page.PageName);
                if (fthumb != null)
                {
                    string extension = Path.GetExtension(fthumb.FileName);
                    string imageName =  Utilities.ToUrlFriendly(page.PageName) + extension;
                    page.Thumb = await Utilities.UploadFile(fthumb, @"pages", imageName.ToLower());
                }
                if (string.IsNullOrEmpty(page.Thumb)) page.Thumb = "default.jpg";
                page.Alias = Utilities.ToUrlFriendly(page.Title);
                page.CreateDate = DateTime.Now;

                _context.Add(page);
                await _context.SaveChangesAsync();
                _notifyService.Success("Create Success");
                return RedirectToAction(nameof(Index));
            }
           
            return View(page);
        }

        // GET: Admin/AdminPages/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var page = await _context.Pages.FindAsync(id);
            if (page == null)
            {
                return NotFound();
            }
            return View(page);
        }

        // POST: Admin/AdminPages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PageId,PageName,Contents,Thumb,Published,Title,MetaDesc,MetaKey,Alias,CreateDate,Ordering")] Page page, IFormFile fthumb)
        {
            if (id != page.PageId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    page.PageName = Utilities.ToTitleCase(page.PageName);
                    if (fthumb != null)
                    {
                        string extension = Path.GetExtension(fthumb.FileName);
                        string image = "thumb_" + Utilities.ToUrlFriendly(page.Title) + "preview" + extension;
                        page.Thumb = await Utilities.UploadFile(fthumb, @"pages", image.ToLower());
                    }
                    if (string.IsNullOrEmpty(page.Thumb)) page.Thumb = "default.jpg";
                    page.Alias = Utilities.ToUrlFriendly(page.PageName);
                    page.CreateDate = DateTime.Now;

                    _context.Update(page);
                    _notifyService.Success("Update Success");
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PageExists(page.PageId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(page);
        }

        // GET: Admin/AdminPages/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var page = await _context.Pages
                .FirstOrDefaultAsync(m => m.PageId == id);
            if (page == null)
            {
                return NotFound();
            }

            return View(page);
        }

        // POST: Admin/AdminPages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var page = await _context.Pages.FindAsync(id);
            _context.Pages.Remove(page);
            _notifyService.Success("Delete Success");
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PageExists(int id)
        {
            return _context.Pages.Any(e => e.PageId == id);
        }
    }
}

E_Commerce/Areas/Admin/Views/AdminPages/Create.cshtml
@model E_Commerce.Models.Page

@{
    ViewData["Title"] = "Tạo mới Pages";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@section Styles{
    <link href="~/AdminAssets/z_SummerNote/summernote-bs4.css" rel="stylesheet">
    <link href="~/AdminAssets/z_SummerNote/summernote.css" rel="stylesheet">
}
<div class="page-header">
    <h2 class="header-title">Quản Lý Pages</h2>
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a asp-area="Admin" asp-controller="AdminPages" asp-action="Index" class="breadcrumb-item">Quản Lý Pages</a>
            <span class="breadcrumb-item active">Tạo mới Pages</span>
        </nav>
    </div>
</div>
<form method="post" asp-area="Admin" asp-controller="AdminPages" asp-action="Create" enctype="multipart/form-data">
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-center justify-content-between">
            <div class="media align-items-center m-b-15">

            </div>
            <div class="m-b-15">
                <button class="btn btn-secondary" asp-area="Admin" asp-controller="AdminPages" asp-action="Index">
                    <i class="anticon anticon-save"></i>
                    <span>Back To List</span>
                </button>
                <button class="btn btn-primary">
                    <i class="anticon anticon-save"></i>
                    <span>Tạo mới PAGE</span>
                </button>
            </div>
        </div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">THÔNG TIN PAGE</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-option">THÔNG TIN SEO</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-description">MÔ TẢ</a>
            </li>
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="PageName">Tên Page</label>
                        <input class="form-control" type="text" asp-for="PageName">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="Ordering">Ordering</label>
                        <input class="form-control" type="number" asp-for="Ordering">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productCategory">Thumb</label>
                        <input type="file" name="fthumb" class="form-control-file" asp-for="Thumb">
                        <span asp-validation-for="Thumb" class="text-danger"></span>
                    </div>
                    <div class="form-group d-flex align-items-center p-t-30">
                        <div class="switch m-r-10">
                            <input type="checkbox" asp-for="Published">
                            <label for="Published"></label>
                        </div>
                        <label>Published</label>
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-option">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productSize">Title</label>
                        <input class="form-control" type="text" asp-for="Title">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productColors">MetaDesc</label>
                        <input class="form-control" type="text" asp-for="MetaDesc">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productFit">MetaKey</label>
                        <input class="form-control" type="text" asp-for="MetaKey">
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-description">
            <div class="card">
                <div class="card-body">
                    <textarea id="summernote" asp-for="Contents">
                </textarea>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts{
    <script src="~/AdminAssets/vendors/select2/select2.min.js"></script>
    <script src="~/AdminAssets/js/pages/e-commerce-product-edit.js"></script>
    <script src="~/AdminAssets/z_SummerNote/summernote-bs4.js"></script>

    <script>
        $('#summernote').summernote({
            placeholder: 'Nhập nội dung',
            tabsize: 2,
            height: 120,
            focus: true,
            minHeight: null,
            maxHeight: null,
            toolbar: [
                ['style', ['style']],
                ['font', ['bold', 'underline', 'clear']],
                ['color', ['color']],
                ['para', ['ul', 'ol', 'paragraph']],
                ['table', ['table']],
                ['insert', ['link', 'picture', 'video']],
                ['view', ['fullscreen', 'codeview', 'help']]
            ]
        });
    </script>
}

E_Commerce/Areas/Admin/Views/AdminPages/Delete.cshtml
@model E_Commerce.Models.Page

@{
    ViewData["Title"] = "Xóa Page";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="page-header">
    <h2 class="header-title">Quản Lý Pages</h2>
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a asp-area="Admin" asp-controller="AdminPages" asp-action="Index" class="breadcrumb-item">Quản Lý Pages</a>
            <span class="breadcrumb-item active">Xác Nhận Xóa Page</span>
        </nav>
    </div>
</div>

<div class="page-header no-gutters has-tab">
    <div class="d-md-flex m-b-15 align-items-center justify-content-between">
        <div class="media align-items-center m-b-15">
            <div class="avatar avatar-image rounded" style="height: 70px; width: 70px">
                <img src="~/images/pages/@Model.Thumb" alt="@Model.Title">
            </div>
            <div class="m-l-15">
                <h4 class="m-b-0">@Model.PageName</h4>
                <p class="text-muted m-b-0">Code: #@Model.PageId</p>
            </div>
        </div>
    </div>
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#product-overview">TỔNG QUAN</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#product-image">Hình Ảnh Sản Phẩm</a>
        </li>
    </ul>
</div>
<div class="container-fluid">
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-overview">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Thông Tin Page: @Model.PageName</h4>
                    <div class="table-responsive">
                        <form asp-action="Delete" asp-controller="AdminPages" asp-route-id="@Model.PageId">
                            <input type="hidden" asp-for="PageId" />
                            <table class="product-info-table m-t-20">
                                <tbody>
                                    <tr>
                                        <td>Page Name:</td>
                                        <td class="text-dark font-weight-semibold">@Model.PageName</td>
                                    </tr>
                                    <tr>
                                        <td>Alias:</td>
                                        <td class="text-dark font-weight-semibold">@Model.Alias</td>
                                    </tr>
                                    <tr>
                                        <td>Trạng Thái:</td>
                                        <td>
                                                <div class="switch m-r-10">
                                                    <input type="checkbox" disabled asp-for="Published">
                                                    <label for="Published"></label>
                                                </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Xác Nhận Xóa Page:</td>
                                        <td>
                                            <input type="submit" value="Delete" class="btn btn-danger"/>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </form>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Thông Tin Mô Tả</h4>
                </div>
                <div class="card-body">
                    @Html.Raw(Model.Contents)
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-image">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <img src="~/images/pages/@Model.Thumb" alt="@Model.Title">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

E_Commerce/Areas/Admin/Views/AdminPages/Details.cshtml
@model E_Commerce.Models.Page

@{
    ViewData["Title"] = "Chi Tiết Page";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="page-header">
    <h2 class="header-title">Quản Lý Pages</h2>
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a asp-area="Admin" asp-controller="AdminPages" asp-action="Index" class="breadcrumb-item">Quản Lý Pages</a>
            <span class="breadcrumb-item active">Chi Tiết Page</span>
        </nav>
    </div>
</div>

<div class="page-header no-gutters has-tab">
    <div class="d-md-flex m-b-15 align-items-center justify-content-between">
        <div class="media align-items-center m-b-15">
            <div class="avatar avatar-image rounded" style="height: 70px; width: 70px">
                <img src="~/images/pages/@Model.Thumb" alt="@Model.Title">
            </div>
            <div class="m-l-15">
                <h4 class="m-b-0">@Model.PageName</h4>
                <p class="text-muted m-b-0">Code: #@Model.PageId</p>
            </div>
        </div>
        <div class="m-b-15">
            <a class="btn btn-secondary" asp-area="Admin" asp-controller="AdminPages" asp-action="Index">Back To List</a>
            <a class="btn btn-primary" asp-area="Admin" asp-controller="AdminPages" asp-action="Edit" asp-route-id="@Model.PageId">Edit</a>
        </div>
    </div>
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#product-overview">TỔNG QUAN</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#product-image">Hình Ảnh Page</a>
        </li>
    </ul>
</div>
<div class="container-fluid">
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-overview">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Thông Tin Page: @Model.PageName</h4>
                    <div class="table-responsive">
                        <table class="product-info-table m-t-20">
                            <tbody>
                                <tr>
                                    <td>Page Name:</td>
                                    <td class="text-dark font-weight-semibold">@Model.PageName</td>
                                </tr>
                                <tr>
                                    <td>Alias:</td>
                                    <td class="text-dark font-weight-semibold">@Model.Alias</td>
                                </tr>
                                <tr>
                                    <td>Trạng Thái:</td>
                                    <td>
                                        <form>
                                            <div class="switch m-r-10">
                                                <input type="checkbox" disabled asp-for="Published">
                                                <label for="Published"></label>
                                            </div>
                                        </form>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Thông Tin Mô Tả</h4>
                </div>
                <div class="card-body">
                    @Html.Raw(Model.Contents)
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-image">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <img src="~/images/pages/@Model.Thumb" alt="@Model.Title" style="height: 450px; width: 500px">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

E_Commerce/Areas/Admin/Views/AdminPages/Edit.cshtml
@model E_Commerce.Models.Page

@{
    ViewData["Title"] = "Chỉnh Sửa Pages";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


@section Styles{
    <link href="~/AdminAssets/z_SummerNote/summernote-bs4.css" rel="stylesheet">
    <link href="~/AdminAssets/z_SummerNote/summernote.css" rel="stylesheet">
}

<div class="page-header">
    <h2 class="header-title">Quản Lý Pages</h2>
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a asp-area="Admin" asp-controller="AdminPages" asp-action="Index" class="breadcrumb-item">Quản Lý Pages</a>
            <span class="breadcrumb-item active">Chỉnh sửa Pages</span>
        </nav>
    </div>
</div>
<form method="post" asp-area="Admin" asp-controller="AdminPages" asp-action="Edit" enctype="multipart/form-data">
    <input type="hidden" asp-for="PageId">
    <input type="hidden" asp-for="Thumb">
    <input type="hidden" asp-for="CreateDate">
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-center justify-content-between">
            <div class="media align-items-center m-b-15">

            </div>
            <div class="m-b-15">
                <button class="btn btn-secondary" asp-area="Admin" asp-controller="AdminPages" asp-action="Index">
                    <i class="anticon anticon-save"></i>
                    <span>Back To List</span>
                </button>
                <button class="btn btn-primary">
                    <i class="anticon anticon-save"></i>
                    <span>Lưu Thay Đổi</span>
                </button>
            </div>
        </div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">THÔNG TIN PAGE</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-option">THÔNG TIN SEO</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-description">MÔ TẢ</a>
            </li>
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="PageName">Tên Page</label>
                        <input class="form-control" type="text" asp-for="PageName">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="Ordering">Ordering</label>
                        <input class="form-control" type="number" asp-for="Ordering">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productCategory">Thumb</label>
                        <input type="file" name="fthumb" class="form-control-file" asp-for="Thumb">
                        <span asp-validation-for="Thumb" class="text-danger"></span>
                    </div>
                    <div class="form-group d-flex align-items-center p-t-30">
                        <div class="switch m-r-10">
                            <input type="checkbox" asp-for="Published">
                            <label for="Published"></label>
                        </div>
                        <label>Published</label>
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-option">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productSize">Title</label>
                        <input class="form-control" type="text" asp-for="Title">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productColors">MetaDesc</label>
                        <input class="form-control" type="text" asp-for="MetaDesc">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productFit">MetaKey</label>
                        <input class="form-control" type="text" asp-for="MetaKey">
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-description">
            <div class="card">
                <div class="card-body">
                    <textarea id="summernote" asp-for="Contents">
                </textarea>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts{
    <script src="~/AdminAssets/vendors/select2/select2.min.js"></script>
    <script src="~/AdminAssets/js/pages/e-commerce-product-edit.js"></script>
    <script src="~/AdminAssets/z_SummerNote/summernote-bs4.js"></script>

    <script>
        $('#summernote').summernote({
            tabsize: 2,
            height: 120,
            focus: true,
            minHeight: null,
            maxHeight: null,
            toolbar: [
                ['style', ['style']],
                ['font', ['bold', 'underline', 'clear']],
                ['color', ['color']],
                ['para', ['ul', 'ol', 'paragraph']],
                ['table', ['table']],
                ['insert', ['link', 'picture', 'video']],
                ['view', ['fullscreen', 'codeview', 'help']]
            ]
        });
    </script>
}

E_Commerce/Areas/Admin/Views/AdminPages/Index.cshtml
@using PagedList.Core.Mvc
@model PagedList.Core.IPagedList<E_Commerce.Models.Page>

@{
    int CurrentPage = ViewBag.CurrentPage;
    ViewData["Title"] = "Danh sách Trang " + CurrentPage;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="page-header">
    <h2 class="header-title">Quản Lý Trang</h2>
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <span class="breadcrumb-item active">Danh sách Trang | Trang: @CurrentPage</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <div>
            <div>
                <a class="btn btn-primary m-b-15" asp-controller="AdminPages" asp-action="Create"><i class="anticon anticon-plus-circle m-r-5"></i>Thêm Pages</a>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-hover e-commerce-table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Tên Page</th>
                        <th>Trạng thái</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null)
                    {
                        foreach (var item in Model)
                        {
                            string url = $"/page/{item.Alias}";
                            <tr>
                                <td>
                                    @item.PageId
                                </td>
                                <td>
                                    <a target="_blank" href="@url">@item.PageName</a>
                                </td>
                                <td>
                                    @if (item.Published == true)
                                    {
                                        <div class="d-flex align-items-center">
                                            <div class="badge badge-success badge-dot m-r-10"></div>
                                            <div>Public</div>
                                        </div>
                                    }
                                    else
                                    {
                                        <div class="d-flex align-items-center">
                                            <div class="badge badge-danger badge-dot m-r-10"></div>
                                            <div>Block</div>
                                        </div>
                                    }
                                </td>

                                <td class="text-right">
                                    <a class="btn btn-success btn-sm m-r-5" asp-area="Admin" asp-controller="AdminPages" asp-action="Details" asp-route-id="@item.PageId">View</a>
                                    <a class="btn btn-warning btn-sm m-r-5 text-black-50" asp-area="Admin" asp-controller="AdminPages" asp-action="Edit" asp-route-id="@item.PageId"><i class="anticon anticon-edit"></i> Update</a>
                                    <a class="btn btn-danger btn-sm m-r-5 text-white" asp-area="Admin" asp-controller="AdminPages" asp-action="Delete" asp-route-id="@item.PageId"><i class="anticon anticon-delete"></i> Delete</a>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
            <div aria-label="Page navigation">
                <ul class="pagination">
                    <pager class="pager-container" list="@Model" asp-action="Index" asp-controller="AdminPages" asp-area="Admin" asp-route-CatID="@ViewBag.CurrentCateID" asp-route-query="@Model" />
                </ul>
            </div>
        </div>
    </div>
</div>